name: staging
services:
  stagingDB:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432
    volumes:
      - stagingDB:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    restart: always
  server:
    depends_on:
      stagingDB:
        condition: service_healthy
    image: ecocochallenge/ecocochallenge-server:staging
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    healthcheck:
      test: 'curl --fail --request GET -H ''content-type:application/json'' --url ''http://localhost:4000/graphql?query=%7B__typename%7D'''
      interval: 5s
      timeout: 5s
      retries: 10

  client:
    image: ecocochallenge/ecocochallenge-client:staging

  nginx:
    depends_on:
      client:
        condition: service_started
      server:
        condition: service_healthy
    image: nginx:1.21.3
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    restart: always

  discord-notifier:
    image: scrip/discord-notifier
    depends_on:
      nginx:
        condition: service_started
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
    command: "npm run send-message 'staging env has been updated : https://github.com/WildCodeSchool/2209-wns-adleman-eco-co-challenges'"

volumes:
  stagingDB: