services:
  db:
    image: postgres:15-alpine
    container_name: ecochallenge_db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecochallenge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  server:
    depends_on:
      db:
        condition: service_healthy
    build: "./server"
    volumes:
      - ./server/src:/app/src
    environment:
      DB_HOST: "db"
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 4000:4000
  client:
     build: './client'
     ports:
       - 3000:3000
     stdin_open: true
     tty: true
     volumes:
       - ./client/src:/app/src    
     command: npm start
     environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
