services:
  db:
    image: postgres:15-alpine
    container_name: ecochallenge_db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecochallenge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
  server:
    depends_on:
      db:
        condition: service_healthy
    build: "./server"
    ports:
      - 4000:4000
    volumes:
      - ./server/src:/app/src
    environment:
      DB_HOST: "db"
      CHOKIDAR_USEPOLLING: "true"
  # client:
  #    build: './client'
  #    ports:
  #      - 3000:3000
  #    volumes:
  #      - ./client/src:/app/src
  #      - ./client/src:/app/src
