name: deploy-staging

on:
    push:
        branches: ["staging"]
    workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_JWT_PRIVATE_KEY: zeyfgzeigfyzegfyuzegf
          envkey_NODE_ENV: "development"
          envkey_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:4000,http://192.168.1.7:4000"
          envkey_SERVER_HOST: "localhost"
          envkey_SERVER_PORT: "4000"
          envkey_DB_HOST: localhost
          directory: server
          file_name: .env
      - name: Run integration test
        run: npm run integration-tests
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_JWT_PRIVATE_KEY: secret
          envkey_NODE_ENV: "development"
          envkey_CORS_ALLOWED_ORIGINS: "http://client:3000"
          envkey_SERVER_HOST: "backend"
          envkey_SERVER_PORT: "4000"
          envkey_DB_HOST: testDB
          envkey_POSTGRES_PASSWORD: postgres
          envkey_REACT_APP_GRAPHQL_API_URL: 'http://backend:4000'
          envkey_BASE_URL: http://client:3000
          envkey_CI: true
          directory: ./
          file_name: .env.e2etests
      - name: Run e2e tests
        run: npm run e2e-tests
  build-and-push-server-staging:
    needs:
      - integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ecocochallenge
          password: ecocochallenge
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:server"
          file: "Dockerfile.production"
          tags: ecocochallenge/ecocochallenge-server:staging
  build-and-push-client-staging:
    needs:
      - e2e-tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ecocochallenge
          password: ecocochallenge
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:client"
          file: "Dockerfile.production"
          tags: ecocochallenge/ecocochallenge-client:staging
  notify:
    needs:
      - build-and-push-server-staging
      - build-and-push-client-staging
    runs-on: ubuntu-latest
    steps:
      - name: Call VPS webhook to update staging
        uses: wei/curl@master
        with:
          args: https://ops.adleman6.wns.wilders.dev/hooks/update-staging