name: deploy-production

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_JWT_PRIVATE_KEY: "zeyfgzeigfyzegfyuzegf"
          envkey_NODE_ENV: "production"
          envkey_CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:4000,http://192.168.1.7:4000"
          envkey_SERVER_HOST: "localhost"
          envkey_SERVER_PORT: "4000"
          envkey_DB_HOST: localhost
          directory: server
          file_name: .env
      - name: Run integration test
        run: npm run integration-tests

  build-and-push-server-production:
    needs:
      - integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ecocochallenge
          password: ecocochallenge
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:server"
          file: "Dockerfile.production"
          tags: ecocochallenge/ecocochallenge-server:production
  build-and-push-client-production:
    needs:
      - integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ecocochallenge
          password: ecocochallenge
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: "{{defaultContext}}:client"
          file: "Dockerfile.production"
          tags: ecocochallenge/ecocochallenge-client:production
  notify:
    needs:
      - build-and-push-server-production
      - build-and-push-client-production
    runs-on: ubuntu-latest
    steps:
      - name: Call VPS webhook to update staging
        uses: wei/curl@master
        with:
          args: https://ops.adleman6.wns.wilders.dev/hooks/update-production