name: Compile and push images

on:
  push:
    branches: ["staging"]
  workflow_dispatch:

jobs:
  client-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ecocochallenge
          password: ecocochallenge
      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx
      - uses: docker/build-push-action@v2
        name: Build and push client image
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ecocochallenge/ecocochallenge-client:staging

  server-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ecocochallenge
          password: ecocochallenge
      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx
      - uses: docker/build-push-action@v2
        name: Build and push server image
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ecocochallenge/ecocochallenge-server:staging
